### ISSUE TITLE
[2.0] lost frame with wireshark

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1763]
Hi

I see the bugs since several days : 

Before this post, i have tested with this example (where i have  used your capture command)  : 
I have 2 VMBox connected to an ethernet switch.
After start the VMs, i start wireshark on a link.
I do traffic between these 2 VMs. I see network frames in wireshark.

I stop traffic and i do something else (drink coffee or a configure config file). I don't wait very long time : 1 or 2 minutes. Perhaps 3.

I do new traffic between theses 2 VMs. Traffic is ok but no new network frame in wireshark.

**Comment by Raizo62** [comment]
2 times that i can't reproduce it.
I hope that i have do an error or the bug is corrected.
I think that you can close it. Except if you can reproduce it (of course ;-))
Sorry for lost time

**Comment by Raizo62** [comment]
Sorry, i lost again frame. I was believing (hoping) it was because i was using a realtime kernel.
But with classic kernel, wireshark loses again frames after somes times.

(I have even removed this message because i could not again reproduce it after reload project. After test "error with cloud", i can see it, but i don't know if it is linked)

**Comment by noplay** [comment]
@grossmj you have the same issue ?

**Comment by grossmj** [comment]
I've tested and could not reproduce it.

Connected 2 VMs to a Ethernet switch. Started the VMs, captured on one of the link, stopped the capture, waited 5 minutes, started a new capture and I could still see traffic flowing between the 2 VMs.

**Comment by grossmj** [comment]
@Raizo62 maybe a video would help... or even screenshots.

Thanks!

**Comment by Raizo62** [comment]
>  captured on one of the link, stopped the capture, waited 5 minutes, started a new capture

no. it is not that : I don't stop the capture, but i don't do traffic.
If i stop wireshark (even if bug) and restart : that works.

**Comment by grossmj** [comment]
You mean you don't stop the capture but stop the traffic from inside the VMs, right?

**Comment by Raizo62** [comment]
I stop the traffic between 2 VMs.
For example, i stop "ping" or services communications. But i don't shutdown interfaces.

**Comment by grossmj** [comment]
Ok, I managed to reproduce the issue.

I used 2 VirtualBox VMs running Linux. I shutdown the interfaces for 5 minutes (ifconfig eth0 down) while a capture is running. After re-enabling them and pinging between the VMs, communication still works but no traffic is captured anymore.

@noplay is it possible the capture monitoring timeouts in the server?

**Comment by grossmj** [comment]
Same issue with 2 VirtualBox VMs connected back to back. Also, I have tested with IOS routers and I have the same problem, hence I think there is globally a problem with capture.

![vbox_02](https://cloud.githubusercontent.com/assets/4752614/21969644/b0d5e090-dbda-11e6-87a2-98fcdea4c05f.png)

The controller shows the capture is still active after 5 mins and re-enabling the interfaces inside the VM.

![vbox_01](https://cloud.githubusercontent.com/assets/4752614/21969632/9f9b842e-dbda-11e6-9184-7aa50dfe2ebd.png)

But nothing new shows up in Wireshark.

![vbox_03](https://cloud.githubusercontent.com/assets/4752614/21969630/9f977f5a-dbda-11e6-9f0e-cc9db9b87040.png)

Looking at the pcap file, it does grow after pinging between the node.

**Comment by noplay** [comment]
If I curl the pcap from api the pcap is updated. This mean the issue is inside the Qt code
