### ISSUE TITLE
GNS3 2.2.0a3 packet capture not working

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2753]
GNS3 2.2.0a3 application and 2.20a3 VM.  Windows 10 Prof and VMware Workstation 14.
Did search of issues but did not find one specific to this.  When I start a Wireshark packet capture Wireshark open, appears to be searching for interfaces, appears to find none and displays no captured packets.  Wireshark packet capture works fine in GNS3 2.1.15.

Wireshark preferences settings:
GNS3 2.1.15
tail.exe -f -c +0b %c | "C:\Program Files\Wireshark\wireshark.exe" -o "gui.window_title:%d" -k -i -
GNS3 2.2.0a3
tail.exe -f -c +0b %c | "C:\Program Files\Wireshark\wireshark.exe" -o "gui.window_title:%d" -k -i -

Thanks!

**Comment by grossmj** [comment]
Hi, between what node types have you tried to capture? Thanks

**Comment by grossmj** [comment]
It should be fixed. Please try again when we release alpha 4. Thanks :+1:

**Comment by jorisc90** [comment]
I'm not 100% sure whether this is a same issue, the result of what is happening does cover the title of this issue.

Remote server, running GNS-VM 2.2a5 (fresh install). Connecting from a Windows 10 terminal (GNS3-client 2.2a5 as well).

Running 2x QEMU (Arista vEOS-lab) images and one GNS3 EthernetSwitch, trying to get pcaps for any link gives me the following error:

`=> Can't create packet capture file /opt/gns3/projects/394d33fb-a222-4b0a-945c-a8f24bfef974/project-files/captures/AristavEOS-lab42151F-2_Ethernet0_to_Ethernetswitch-1_Ethernet2.pcap: [Errno 2] No such file or directory: '/opt/gns3/projects/394d33fb-a222-4b0a-945c-a8f24bfef974/project-files/captures/AristavEOS-lab42151F-2_Ethernet0_to_Ethernetswitch-1_Ethernet2.pcap'
`
Retrying to capture and/or trying to open the capture does not fix the issue.

This seems odd because when I check the folder on the GNS3-VM:

`gns3@gns3vm:/opt/gns3/projects/394d33fb-a222-4b0a-945c-a8f24bfef974/project-files/captures$ ls -l
total 7216
-rw-rw---- 1 gns3 gns3 7388923 May  6 13:01 AristavEOS-lab42151F-2_Ethernet0_to_Ethernetswitch-1_Ethernet2.pcap
` 

Any pointers?

**Comment by cioby23** [comment]
Yes I can confirm I experience the same bug using a remote GNS3 server (2.2.0a5) no matter which type of devices I connect (Qemu, Dynamips, Docker).

**Comment by sliddjur** [comment]
This bug is still present as of 2.2.7. 
`gns3vm:/opt/gns3/projects/5b441f9a-54f5-4f72-af65-320fd6762c89/project-files/captures/ls01_em3_to_ss01_em3.pcap` is getting data, but wireshark on client suddenly stops updating.

Remote vm in esxi.
Client in ubuntu from ppa version 2.2.7
