### ISSUE TITLE
Setup wizard is very user unfriendly during server setup

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2846]
**Describe the bug**
The setup wizard is very user unfriendly during server setup, see attached video.
- During the first seconds in local server configuration (video: 0:15 - 0:23) it's impossible to use the GUI due to multiple "Please wait" popups.
- Then the wizard shows the error message, that the server at 127.0.0.1 is not reachable, even though the Windows 2008R2 firewall should not block this local connection. Even switching off the firewall doesn't help. And I had no antivirus solution installed, not even the MS Defender. An user not familiar with GNS3 might probably stop here and start debugging his system, even though there's nothing wrong.
- The host binding is set by default to 169.254.x.y, this address range should not be used, use 127.0.0.1 instead.
- After existing the local server configuration with the "Next>" button (video: 0:31) the interface is blocked for several seconds until a "Connecting to server ..." popup is shown.

This creates a very bad first impression of GNS3, currently I suggest users to exit the setup wizard as fast as possible and use the "normal" preferences.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 2008R2
 - GNS3 version 2.1.21
 - only local server

**To Reproduce**
1. First start of GNS3 after installation

**Screenshots or videos**
[gns3_setup.mp4](https://gist.github.com/b-ehlers/83bd4201a35a93dab43fabdb51bf82b6/raw/f27c459a0e748021e994ead91e762c6d9d67a3ba/gns3_setup.mp4)

**Additional context**
This is not windows specific, I had similar experience with installations on other OS.

**Comment by grossmj** [comment]
I agree, the setup wizard is so unfriendly. I will check if we can make some quick improvement but to be honest I think we should refactor that part completely.

I am also looking into using asynchronous I/O (asyncio Python module) with Qt for a major redesign of the current desktop GUI, one priority is to not have all these progress dialogs popping up, especially than hitting cancel usually doesn't help.

**Comment by b-ehlers** [comment]
Sure, a complete rewrite is something for 2.3.

But maybe you can have a look at the two major issues:
- Fix the message telling the user that 127.0.0.1 is not reachable. It should help not trying to start the gns3server until the user enters/confirms the IP address of the server. That should also prevent these Please wait" popups during the server IP dialog.
- Avoid these 169.254.x.y, addresses selected by default.

**Comment by grossmj** [comment]
> Sure, a complete rewrite is something for 2.3.

Indeed, this won't be for 2.2 and even 2.3 I think

> But maybe you can have a look at the two major issues.

Thanks, I am gonna try to address these.

**Comment by grossmj** [comment]
I noticed that we already avoid link local addresses in version 2.2: https://github.com/GNS3/gns3-gui/blob/210cf63fe2265651f5b818c1ba30293618514063/gns3/dialogs/setup_wizard.py#L85 and also we do not try to start the gns3server when the setup wizard is launched: https://github.com/GNS3/gns3-gui/blob/210cf63fe2265651f5b818c1ba30293618514063/gns3/main_window.py#L1198

This should solve the most annoying issues you have reported. Nonetheless, the wizard needs a good review/rewrite.

**Comment by b-ehlers** [comment]
That sounds great. Maybe the `Bug` label can be removed, now there are mainly some enhancements needed.

**Comment by b-ehlers** [comment]
Just tested 2.2.0rc3, which should include both of the changes you mentioned. The host binding to 169.254.x.y is indeed fixed. But the bug, that GNS3 tries to start the gns3server before its configuration, is still there. So except with the private addresses it is still as annoying as it always was.

**Comment by grossmj** [comment]
This should work in our latest nightly build: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2019-08-30/2.2/GNS3-2.2.2019-08-30-all-in-one.exe/download

You may have to uninstall GNS3 completely to trigger the setup wizard again. Or you can access it via the help menu.

**Comment by b-ehlers** [comment]
I triggered the wizard by deleting `AppData\Roaming\GNS3`. But no, that nightly build doesn't change anything.

First: The nightly build are quite likely created from the 2.2 branch. but you are adding your changes to the master branch. Therefore this nightly doesn't include the question, if the user wants to see the wizard again (https://github.com/GNS3/gns3-gui/commit/210cf63fe2265651f5b818c1ba30293618514063).

Second: I see no reason, why this question at the end of the wizard should change anything at the begin of the wizard.

**Comment by grossmj** [comment]
> First: The nightly build are quite likely created from the 2.2 branch. but you are adding your changes to the master branch. Therefore this nightly doesn't include the question, if the user wants to see the wizard again (210cf63).

You are right, our nightly build is still created from 2.2 branch. I have merged the changes now.

> Second: I see no reason, why this question at the end of the wizard should change anything at the begin of the wizard.

The default behavior was to not show the wizard again if the local server was successfully started. The local server is not started if the setup wizard is executed: https://github.com/GNS3/gns3-gui/blob/2.2/gns3/main_window.py#L1198

**Comment by b-ehlers** [comment]
Just tested with 2.2.0rc4, same result. Here a video: [gns3_setup_22rc4.mp4](https://gist.github.com/b-ehlers/e320b871de53ff04895a17a72b001206/raw/6bf5d00cd224e0c58cb33ed9792f2d62b0c9bfbf/gns3_setup_22rc4.mp4)

It still shows the error message about the server 127.0.0.1 not reachable. Furthermore the wizard doesn't fit anymore on a 1024x768 screen. And personally I don't like the additional question, if I want to run the wizard again.

But I noticed one thing: When I stay at the first screen of the wizard (select server type) until all those "Please wait" popups cease to appear, the dreadful error message is not shown.

My personal feeling is, that you should stop making changes to v2.2 and continue working on this issue on a later version.

**Comment by grossmj** [comment]
I have simplified the setup wizard for version 3.0

There is only 2 options, start a local controller (Linux only) or connect to a remote controller.

![Screenshot from 2021-12-27 17-36-27](https://user-images.githubusercontent.com/4752614/147444760-3d9bd554-bd55-4dc0-b561-e528a9bcd88f.png)

This is for the local controller option:

![Screenshot from 2021-12-27 17-36-37](https://user-images.githubusercontent.com/4752614/147444755-967f9cea-9d7a-442d-8e0a-dea032db4548.png)

This is for the remote controller option:

![Screenshot from 2021-12-27 17-36-49](https://user-images.githubusercontent.com/4752614/147444752-34217ab4-eb1c-4684-a132-d389ce260a28.png)

There is one summary page at the end (for both options):

![Screenshot from 2021-12-27 17-37-04](https://user-images.githubusercontent.com/4752614/147444745-a6b578ca-9fb7-4e5b-9249-4f3f2fd212af.png)

Everything should work a lot more smoothly with no "Please wait" popups consistently showing up...
