### ISSUE TITLE
GNS3 2.2.3 cannot create custom version of template appliance

### ISSUE THREAD

**Issue by sliddjur** [GNS3/gns3-gui#2905]
**Describe the bug**

As per the documentation, it should be possible to create custom versions of appliances. However, since 2.2 the button is no longer there.

**GNS3 version and operating system (please complete the following information):**
 - OS: Ubuntu 19.10
 - GNS3 version. 2.2.3
 - Local server

**To Reproduce**
Add template
install appliance from gns3 server
select appliance vyos
install on local computer
qemu library default
here, the button is gone to create new versions.

**Screenshots or videos**
screenshot and community discussion
https://www.gns3.com/community/discussion/create-a-new-version-for-an-appl
does not help to add custom version in gns3a files on server either, in file: `/usr/share/gns3/gns3-server/lib/python3.7/site-packages/gns3server/appliances/vyos.gns3a`

https://www.gns3.com/community/discussion/how-do-i-create-a-custom-version

**Additional context**
official documentation
https://docs.gns3.com/1RpM21DdgL2pCNtIrw6e9Yf52tRjYZIe46LMeESl-jy4/

**Comment by addy90** [comment]
I can confirm the issue with 2.2.5, I tried everything but the button is missing.

**Comment by sliddjur** [comment]
Nice find  @addy90, in my opinion its needed, because GNS3 team cannot manage to create and update all versions of all images for all appliances that are available.

**Comment by addy90** [comment]
@sliddjur yes you are right, GNS3 team cannot manage this, and this is why being able to create custom versions is so important for end users like use, **because** GNS3 team cannot do this.

The current workaround is to create a custom gns3a file, so you still can use custom versions, but it needs a lot more time than just enabling the button to create a new version. I don't know why the button was deactivated... I don't find it confusing, or better: if it is confusing, extend the help files and documentation, than it will not be confusing anymore... :)

**Comment by sliddjur** [comment]
@addy90 I tried creating a custom gns3a file for my install before,, but it never showed up. Where did you put it? Im on ubuntu using the ppa.

**Comment by addy90** [comment]
@sliddjur 
I can select a custom appliance file when I add a "New template" on Windows 10, it should be the same on Ubuntu.
In my case, I used one of the existing gns3a files, customized it with my image and imported it here. Worked. But it was inconvenient compared to the "new version" button that was enabled before in 2.1.

![grafik](https://user-images.githubusercontent.com/6824664/72888545-0fac2d80-3d0e-11ea-829e-b73925de29f6.png)

**Comment by sliddjur** [comment]
@addy90 I finaly got time to look at this, however, I get an error saying I am missing the qcow2 file.
That file does exist in my system though...
```
$ find ~ -name empty8G.qcow2
/home/olof/GNS3/images/QEMU/empty8G.qcow2
```

And my gns3a file looks like this;
```
{
    "name": "VyOS",
    "category": "router",
    "description": "VyOS is a community fork of Vyatta, a Linux-based network operating system that provides software-based network routing, firewall, and VPN functionality. VyOS has a subscription LTS version and a community rolling release.  The latest version in this appliance is in the rolling release track.",
    "vendor_name": "Linux",
    "vendor_url": "http://vyos.net/",
    "documentation_url": "http://vyos.net/wiki/User_Guide",
    "product_name": "VyOS",
    "product_url": "http://vyos.net/",
    "registry_version": 3,
    "status": "stable",
    "symbol": "vyos.png",
    "maintainer": "GNS3 Team",
    "maintainer_email": "developers@gns3.net",
    "usage": "Default username/password is vyos/vyos. At first boot the router will start from the cdrom, login and then type install system and follow the instructions.",
    "port_name_format": "eth{0}",
    "qemu": {
        "adapter_type": "e1000",
        "adapters": 3,
        "ram": 512,
        "arch": "x86_64",
        "console_type": "telnet",
        "boot_priority": "dc",
        "kvm": "allow"
    },
    "images": [
        {
            "filename": "vyos-1.2.5-epa1-amd64.iso",
            "version": "1.2.5-epa1",
            "md5sum": "4c85f6c4b05ad5ab351106aaeb5e16a0",
            "filesize": 404750336,
            "download_url": "https://downloads.vyos.io/?dir=release/1.1.8",
            "direct_download_url": "https://downloads.vyos.io/release/1.1.8/vyos-1.1.8-amd64.iso"
        }
    ],
    "versions": [
        {
            "name": "1.2.5-epa1",
            "images": {
                "hda_disk_image": "empty8G.qcow2",
                "cdrom_image": "vyos-1.2.5-epa1-amd64.iso"
            }
        }
    ]
}

```

**Comment by addy90** [comment]
@sliddjur 
Maybe you have to select the image in the dialog where it is stated "missing" via "Import" button.
When I use the GNS3 VM I need to import each image and iso to the VM via the Import button. Maybe the qcow2 image is existing, but in the wrong path for GNS3. The Import button copies it to the right location for GNS3 - no matter if VM or local.
I am not sure how your setup is exactly configured, but the Import button should solve it...

**Comment by grossmj** [comment]
Thanks for your input guys :+1: The "create a new version" button will be back in GNS3 version 2.2.6

**Comment by sliddjur** [comment]
@grossmj its still not working properly. its importing the appliance with the wrong file name. see gif I created. It uses the name of an already present from the registry .

![vyos](https://user-images.githubusercontent.com/10002057/80101442-b1dbeb80-8571-11ea-883e-879109426f13.gif)

thanks

**Comment by lemmehisss** [comment]
ISSUE FIXED :

if you guys still stuck. I fixed this issue by changing the GNS3a file . you do not need the " new version" tab to install it. I have attached the file for 8.3.150 vWLC version ( gns3a template file ).Just copy paste the below in notepad and change the file extension to .gns3a

{
    "name": "Cisco vWLC",
    "category": "guest",
    "description": "The Virtual Wireless Controller can cost-effectively manage, secure, and optimize the performance of local and branch wireless networks. Ideal for small and medium-sized businesses, the Virtual Wireless Controller facilitates server consolidation and improves business continuity in the face of outages.",
    "vendor_name": "Cisco",
    "vendor_url": "http://www.cisco.com/",
    "documentation_url": "http://www.cisco.com/c/en/us/products/wireless/wireless-lan-controller/index.html",
    "product_name": "Virtual Wireless LAN Controller",
    "product_url": "http://www.cisco.com/c/en/us/support/wireless/virtual-wireless-controller/tsd-products-support-series-home.html",
    "registry_version": 3,
    "status": "experimental",
    "maintainer": "GNS3 Team",
    "maintainer_email": "developers@gns3.net",
    "usage": "Starting vWLC will start an installation of vWLC onto a blank 8GB Drive.",
    "first_port_name": "ServicePort",
    "port_name_format": "Management{port1}",
    "symbol": ":/symbols/wlan_controller.svg",
    "qemu": {
        "adapter_type": "e1000",
        "adapters": 2,
        "ram": 2048,
        "hda_disk_interface": "ide",
        "arch": "x86_64",
        "console_type": "vnc",
        "boot_priority": "cd",
        "kvm": "require",
        "options": ""
    },
    "images": [    
        {
            "filename": "Cisco-vWLC-AIR-CTVM-7-3-101-0-file1.iso",
            "version": "7.3.101.0",
            "md5sum": "6bf17dceaf46e57aab0fb0d43eb6ea06",
            "filesize": 157900800,
            "download_url": "https://software.cisco.com/download/release.html?mdfid=284464214&flowid=&softwareid=280926587&release=7.3.101.0"
        },
        {
            "filename": "AIR-CTVM-7-6-110-0-file1.iso",
            "version": "7.6.110.0",
            "md5sum": "7acbd88120f008a25d849b72b7207e92",
            "filesize": 185561088,
            "download_url": "https://software.cisco.com/download/release.html?mdfid=284464214&flowid=&softwareid=280926587&release=7.6.110.0"
        },
        {
            "filename": "AIR-CTVM-k9-8-1-120.0.iso",
            "version": "8.1.120.0",
            "md5sum": "477363f88f07f64499bb4ab80ffa9d2f",
            "filesize": 302104576,
            "download_url": "https://software.cisco.com/download/release.html?mdfid=284464214&flowid=&softwareid=280926587&release=8.1.120.0"
        },
        {
            "filename": "MFG_CTVM_8_2_141_0.iso",
            "version": "8.2.141.0",
            "md5sum": "29483229ce7844df55a90564b077c958",
            "filesize": 351156224,
            "download_url": "https://software.cisco.com/download/release.html?mdfid=284464214&flowid=&softwareid=280926587&release=8.2.141.0"
        },
        {
            "filename": "MFG_CTVM_8_3_102_0.iso",
            "version": "8.3.102.0",
            "md5sum": "7f6b7968b5bed04b5ecc119b6ba4e41c",
            "filesize": 365996032,
            "download_url": "https://software.cisco.com/download/release.html?mdfid=284464214&flowid=&softwareid=280926587&release=8.3.102.0"
        },
        {
            "filename": "MFG_CTVM_8_3_150_0.iso",
            "version": "8.3.102.0",
            "md5sum": "7f6b7968b5bed04b5ecc119b6ba4e41c",
            "filesize": 365996032,
            "download_url": "https://software.cisco.com/download/home/284464214/type/280926587/release/8.3.150.0"
        },
        {
            "filename": "empty8G.qcow2",
            "version": "1.0",
            "md5sum": "f1d2c25b6990f99bd05b433ab603bdb4",
            "filesize": 197120,
            "download_url": "https://sourceforge.net/projects/gns-3/files/Empty%20Qemu%20disk/",
            "direct_download_url": "https://sourceforge.net/projects/gns-3/files/Empty%20Qemu%20disk/empty8G.qcow2/download"
        }
    ],
    "versions": [

        {
            "name": "8.1.120.0",
            "images": {
                "hda_disk_image": "empty8G.qcow2",
                "cdrom_image": "AIR-CTVM-k9-8-1-120.0.iso"
            }
        },
        {
            "name": "8.2.141.0",
            "images": {
                "hda_disk_image": "empty8G.qcow2",
                "cdrom_image": "MFG_CTVM_8_2_141_0.iso"
            }
        },
        {
            "name": "8.3.102.0",
            "images": {
                "hda_disk_image": "empty8G.qcow2",
                "cdrom_image": "MFG_CTVM_8_3_102_0.iso"
            }
        } ,
        {
            "name": "8.3.150.0",
            "images": {
                "hda_disk_image": "empty8G.qcow2",
                "cdrom_image": "MFG_CTVM_8_3_150_0.iso"
            }
        }    
    ]
}
