### ISSUE TITLE
Key Error :'vendor_id'  on GNS3 2.2.11 with VirtualBox on Ubuntu 20.04

### ISSUE THREAD

**Issue by medharrak** [GNS3/gns3-gui#3018]
Hi,
By trying to configure Virtualbox on GNS3 I get the following error : 
Error while listing vms: Traceback (most recent call last):
File "/usr/share/gns3/gns3-server/lib/python3.8/site-packages/gns3server/web/route.py", line 198, in control_schema
await func(request, response)
File "/usr/share/gns3/gns3-server/lib/python3.8/site-packages/gns3server/handlers/api/controller/gns3_vm_handler.py", line 52, in get_vms
vms = await Controller.instance().gns3vm.list(request.match_info["engine"])
File "/usr/share/gns3/gns3-server/lib/python3.8/site-packages/gns3server/utils/asyncio/__init__.py", line 163, in wrapper
return await f(oself, *args, **kwargs)
File "/usr/share/gns3/gns3-server/lib/python3.8/site-packages/gns3server/controller/gns3vm/__init__.py", line 262, in list
for vm in (await engine.list()):
File "/usr/share/gns3/gns3-server/lib/python3.8/site-packages/gns3server/controller/gns3vm/virtualbox_gns3_vm.py", line 216, in list
await self._check_requirements()
File "/usr/share/gns3/gns3-server/lib/python3.8/site-packages/gns3server/controller/gns3vm/virtualbox_gns3_vm.py", line 95, in _check_requirements
vendor_id = cpu_info['vendor_id']
KeyError: 'vendor_id'

**Comment by zebrajr** [comment]
Getting a similar error while trying to setup GNS3 with VirtualBox in Windows 10 Version 1909 Build 18363.418

Error while listing vms: Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 198, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\gns3_vm_handler.py", line 52, in get_vms
  File "./gns3-server\gns3server\utils\asyncio\__init__.py", line 163, in wrapper
  File "./gns3-server\gns3server\controller\gns3vm\__init__.py", line 262, in list
  File "./gns3-server\gns3server\controller\gns3vm\virtualbox_gns3_vm.py", line 216, in list
  File "./gns3-server\gns3server\controller\gns3vm\virtualbox_gns3_vm.py", line 95, in _check_requirements
KeyError: 'vendor_id'

**Comment by grossmj** [comment]
I found the issue, starting with version 6.0.0, the "vendor_id" field returned by `get_cpu_info()`  from the `py-cpuinfo` module has been renamed to "vendor_id_raw"

https://github.com/workhorsy/py-cpuinfo/commit/9e79e59682acc127446bebec27f716e3e10e961e#diff-edb26df606454fa32fe0d745d893abdf

One workaround, depending how you installed GNS3, may be to downgrade to py-cpuinfo version 5.0.0

```
sudo python3 -m pip install py-cpuinfo==5.0.0
```

**Comment by medharrak** [comment]
I did the install using GNS3 doc : install from repository sudo add-apt-repository ppa:gns3/ppa

**Comment by grossmj** [comment]
This should be fixed now however you will probably have to wait for the next release to use the GNS3 VM directly. In the meantime you can manually start the GNS3 VM in VirtualBox before you start GNS3.

Then configure as a remote GNS3 VM in the preferences:

![Screenshot from 2020-07-10 17-48-18](https://user-images.githubusercontent.com/4752614/87132922-b6dd4b00-c2d5-11ea-875d-d990519003ff.png)

![Screenshot from 2020-07-10 17-49-01](https://user-images.githubusercontent.com/4752614/87132931-bb096880-c2d5-11ea-8a8d-0d3e72c2f86c.png)

OR just use the GNS3 VM as the main server (easier as everything will run inside the VM).

![Screenshot from 2020-07-10 17-48-49](https://user-images.githubusercontent.com/4752614/87133009-dc6a5480-c2d5-11ea-9f4d-d4561dcfe029.png)

**Comment by medharrak** [comment]
Thank you

**Comment by MrWolf1973** [comment]
Thank you
I can confirm that the workaround is functional on
Intel i7-4790k
GNS3 2.2.11
VirtualBox 6.1.10
Win10 Pro Ver 2004

**Comment by izharkazmi** [comment]
Thanks a lot  - temporary fix worked for me too.

Intel i9-9880H
GNS3 2.2.11
VirtualBox 6.1
Win10 Pro Build 18363

**Comment by akyumurkov** [comment]
I followed the exact instructions and the damn think still do not want to connect (connection timeout). Am I missing sth?

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
GNS3 2.2.11
Virtual Box 6.1
Win 10 Pro 20H2  Ver19042.300
