### ISSUE TITLE
GNS3 (2.2.20) AUTOMATIC link creation PROBLEM!!!  "Error while creating link: Cannot connect to itself"

### ISSUE THREAD

**Issue by HusseinNadjafli** [GNS3/gns3-gui#3169]
Hello.

I am facing such a problem in GNS3 (2.2.20). This is the problem:

Whenever I try to create a connection by clicking a router, switch or any device, it gives me an error:

**`"Error while creating link: Cannot connect to itself".`**

And I can only choose the interface when I keep it printed on the device. However, in previous versions, when I click on the "Add a link" command and then click on the device, interfaces appear (that is, it was waiting for me to choose which interface) and then I could easily choose which interface I wanted.

**SO GNS3 DOES NOT WAIT FOR ME TO CHOOSE MY INTERFACE, IT SELECTED IT AUTOMATICALLY.** HOW CAN I SOLVE THIS PROBLEM?

THANKS IN ADVANCE !!!

https://user-images.githubusercontent.com/37479879/115363839-dc3ba580-a1d3-11eb-94eb-f4fd7f9aeff3.mp4

**_Note:_** 
Sometimes when I click on the device, GNS3 waits for me to select the interface, sometimes it selects itself automatically and causes errors.

**OS: Windows 10 20H2 (19042.928) 
GNS3 version: 2.2.20
GNS3 VM version: 2.2.20**

**Comment by Hussein908** [comment]
@grossmj Please, solve the problem.
Thanks 😊

**Comment by eantowne** [comment]
@grossmj Is this intended behavior? Left-click and hold brings up the interface selection context menu, but simply clicking seems to bypass the menu. Is this perhaps an issue with QT?

**Comment by Hussein908** [comment]
**@grossmj I think this problem must be solved. :)**

**Comment by grossmj** [comment]
This may be due to a bug in Qt. Do you have the same problem with GNS3 v2.2.19?

**Comment by B3r3n06** [comment]
Since 2.2.20, I see that heavy client, right click without being kept clicked, no menu is opening when linking objects. So when clicking again because you think you did it bad, it falls into that error.
With 2.2.20, you must link pushing right mouse, keeping it pushed until menu and then you can step forward...
Maybe that's the same issue ?

**Comment by Hussein908** [comment]
@B3r3n06 , @grossmj Yes, I can only select a link when I hold down the right click. This is not good either. In 2.2.19 version, when I right click, the menu opens, I can easily select the interface and extend it and right click on the device I want. And the menu was opened on that device, and I could easily select my interface and create a connection.

**Comment by Hussein908** [comment]
@grossmj No, that can't be. Version `2.2.21` has arrived, but still has the same problem. Mr.Jeremy Grossman , when exactly will this error be resolved? Or what can I do for this error?
I have `Pyhton 3.9.5` installed on my computer. Could this cause the error?

**Comment by realcapo** [comment]
Hi everyone,  just letting you know that the issue is still there in version 2.2.21. I've downgraded back to  the x.x.19 version. Hopefully it can be fixed on the next update.

**Comment by HusseinNadjafli** [comment]
The versions of Qt and PyQt running GNS3 2.2.19 version are as follows:
![gns3 screen](https://user-images.githubusercontent.com/37479879/118477875-43d80880-b720-11eb-8abe-7ea244aa1a8e.PNG)

**Comment by grossmj** [comment]
Fixed.

**Comment by HusseinNadjafli** [comment]
> Fixed.

Very good. Should we install version 2.2.21?

**Comment by grossmj** [comment]
The fix will be included in version 2.2.22 (to be released).

**Comment by HusseinNadjafli** [comment]
> The fix will be included in version 2.2.22 (to be released).

Very good, very good. You are the genius of GNS3👍. Thank you.

**Comment by Mario156090** [comment]
@grossmj 
This error persist in 2.24.
Windows 10 19043.1202.
